# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('review_count', models.CharField(max_length=10)),
                ('star', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=30)),
                ('checkin_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('business_id', models.CharField(max_length=30)),
                ('star', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('review_count', models.CharField(max_length=10)),
            ],
        ),
    ]
