# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=30)),
                ('customer_flow', models.CharField(max_length=30)),
                ('avg_rating', models.CharField(max_length=30)),
                ('avg_ratings', models.CharField(max_length=100)),
            ],
        ),
    ]
