# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_checkin_analysis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_yelp',
        ),
    ]
